### ISSUE TITLE
QR Code generator doesn`t work.

### ISSUE THREAD

**Issue by PingWIN7** [muon-emergency/project-fob#19]
Probably a porting issue but it does not crash the whole project when clicked on it.

**Comment by WilkaH** [comment]
The library that was used for QR code generating doesn't work in .NET Core, so we commented that code out for now: https://github.com/muon-emergency/project-fob/blob/ac8659cfbbc39e078d324d7c12a6a89f7331491f/project-fob/Controllers/HomeController.cs#L230-L243

**Comment by WilkaH** [comment]
@PingWIN7 this is fixed now, right?

**Comment by PingWIN7** [comment]
I thought I closed this one already. 
Yes… kinda, there is a small bug which was found during the unit testing but other than that it should be fine. I’m not closing this issue at the moment as I want to try out linking the issue when I create the pull request.
