### ISSUE TITLE
Creating multiple meeting

### ISSUE THREAD

**Issue by PingWIN7** [muon-emergency/project-fob#30]
Situation: Someone hosting 2 meeting in the same time.

Issue: For most of the features we are storing values in sessions. Because the user is hosting a different meeting the values are being overwritten. Because of this some functions become faulty. (For example the newly implemented QR code generator, stat screens can return wrong values. Host may accidentally shuts down the last meeting instead of the other one. etc.

**Comment by WilkaH** [comment]
At some point we're going to stop storing things in session state, so this can be ignored for now. It should go away once we've changed the storage method.
