### ISSUE TITLE
Validations for all (toLower)

### ISSUE THREAD

**Issue by PingWIN7** [muon-emergency/project-fob#6]
Might be related to the enter room method.

**Comment by PingWIN7** [comment]
Description does not explains it.: This was created as we had a bit of a concern about the meeting id won't be easily readable. The issue here is that in case someone enters the room ID without using capslock (or similar) they won't be able to enter as they used lower case letters.

**Comment by WilkaH** [comment]
As well as make sure all checks are case insensitive, we could also generate the codes using unambiguous characters (i.e. ones that are hard to misread). https://github.com/swanson/friendly_code does it from the set of "3 6 7 C D F G H J K M N P R T W X" which seems like a reasonable and gives you 17 possible values at each position.

It's also nice, from a usability point of view, to break the chars up for easier reading. Groups of 3 are pretty common and we used 3 groups of 3 (e.g. "3FG-CDR-T6X") that'll give 118587876497 possible values which should be plenty :)

If the user does type in the "-" which should remove them (they're only there for a UI), and don't require those parts.

**Comment by PingWIN7** [comment]
Should I be concerned about duplicates?
The odds for this to happen is around 1:101,559,956,668,416 in case if it's length is 9 with the current implementation but with an unambiguous characters it'll be 1:24,137,569 for 6 character and 1:118,587,876,497 for 9 characters. (If I counted it correctly)

**Comment by PingWIN7** [comment]
Added an unambiguous meetingIDGenerator (Implemented it by copying an existing generator and replaced the characters). For the main screen it should not be case sensitive anymore.
